version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 First.py
  test:
    working_directory: ~/secondProject-1
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout 
      - run: python3 Test.py
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
