version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/python:3.6.4"

    steps:
      - run:
          name: Trigger the Build Job
          command: |
            printf "Triggering an $PROJECT build on the $CIRCLE_BRANCH branch\n\n"

            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/Kamsapphire/secondProject-1/tree/main?circle-token=bbcd49a94bf78b00cf41c572a0f715e35ed68898")

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/$ORGANIZATION/$PROJECT/tree/$BRANCH"
            
  build_test:
    docker:
      - image: "cirlceci/python:3.6.4"
    steps:
      - checkout
      - run: python3 Test.py